### ISSUE TITLE
MySQL init process failed

### ISSUE THREAD

**Issue by arbreezy** [techdivision/magento2-docker-imgen#15]
Hello,
I tried to generate a magento image following the steps in your README file. MySQL isn't able to start for some reason and fails after a while due to [this] code snippet I guess. Any ideas why this happens?
Do I need to specify sth in my docker image for MySQL?

[this]: https://github.com/techdivision/dnmp-debian/blob/stretch/fs/usr/local/bin/mysql_start

**Comment by zelgerj** [comment]
Should be fixed by last PR (#16). Thanks to @wagnert :+1: :1st_place_medal:
